#!/usr/bin/env python3
"""Check Python 3 syntax against a shrinking baseline.

Large parts of ``Python/src`` are still Python 2 — ``print`` statements,
``except E, e:``, implicit relative imports. That is documented, expected, and
tracked; it is not something an individual pull request caused.

A plain "does it all compile" check is therefore useless here: it would be red
on every pull request for reasons unrelated to the change, and a check that is
always red is one that everybody learns to ignore. Deleting the check instead
would be worse — the Python 2 code would then rot unobserved.

So this ratchets. It records the files known to fail in a baseline and fails
only on:

- a **regression** — a file that used to compile and now does not, which is
  something the current change did cause; or
- a **stale baseline entry** — a file that now compiles but is still listed.
  Failing on this is what stops the baseline from silently becoming a
  permanent excuse: fixing a file *requires* removing its line, so the list
  can only ever shrink.

Usage::

    python tools/check_python3_syntax.py Python/src/pymodelica Python/src/pyjmi
    python tools/check_python3_syntax.py --update Python/src/...   # re-record

The baseline lives in ``tools/python3_baseline.txt``.
"""

from __future__ import annotations

import argparse
import os
import sys
import warnings
from pathlib import Path

DEFAULT_BASELINE = Path(__file__).parent / "python3_baseline.txt"


def find_python_files(roots: list[Path]) -> list[Path]:
    files: list[Path] = []
    for root in roots:
        if root.is_file() and root.suffix == ".py":
            files.append(root)
        elif root.is_dir():
            files.extend(sorted(root.rglob("*.py")))
    return files


def fails_to_compile(path: Path) -> str | None:
    """Return a one-line reason if *path* is not valid Python 3, else None."""
    try:
        source = path.read_bytes()
    except OSError as exc:
        return f"unreadable: {exc}"

    try:
        # Only syntax errors matter here. Legacy sources raise a great many
        # SyntaxWarnings — invalid escape sequences in LaTeX-bearing docstrings,
        # `is` against int literals — and letting those print would bury the
        # errors under hundreds of lines of noise.
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            compile(source, str(path), "exec")
    except SyntaxError as exc:
        return f"{exc.msg} (line {exc.lineno})"
    except ValueError as exc:
        # e.g. a source file containing null bytes.
        return f"invalid source: {exc}"
    return None


def load_baseline(path: Path) -> set[str]:
    if not path.is_file():
        return set()
    entries = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            entries.add(line)
    return entries


def write_baseline(path: Path, failing: dict[str, str]) -> None:
    lines = [
        "# Files that are not yet valid Python 3.",
        "#",
        "# Generated by tools/check_python3_syntax.py --update. This list may",
        "# only ever shrink: CI fails if a listed file starts compiling and is",
        "# not removed from here, so progress cannot be quietly undone.",
        "#",
        f"# {len(failing)} file(s) remaining.",
        "",
    ]
    lines.extend(f"{name}  # {reason}" for name, reason in sorted(failing.items()))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def annotate(path: str, message: str, *, level: str = "error") -> None:
    if os.environ.get("GITHUB_ACTIONS") == "true":
        print(f"::{level} file={path}::{message}")
    else:
        print(f"{level.upper()}: {path}: {message}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("roots", nargs="+", type=Path)
    parser.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    parser.add_argument(
        "--update",
        action="store_true",
        help="rewrite the baseline from the current state instead of checking",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path("."),
        help="paths are recorded relative to this (default: current directory)",
    )
    args = parser.parse_args()

    repo_root = args.repo_root.resolve()
    failing: dict[str, str] = {}
    checked = 0

    for path in find_python_files(args.roots):
        checked += 1
        reason = fails_to_compile(path)
        if reason is not None:
            try:
                name = path.resolve().relative_to(repo_root).as_posix()
            except ValueError:
                name = path.as_posix()
            failing[name] = reason

    if args.update:
        write_baseline(args.baseline, failing)
        print(f"Recorded {len(failing)} failing file(s) in {args.baseline}.")
        return 0

    baseline = load_baseline(args.baseline)
    # Baseline lines carry a trailing "  # reason" comment; strip it.
    baseline = {entry.split("  #")[0].strip() for entry in baseline}

    regressions = sorted(set(failing) - baseline)
    fixed = sorted(baseline - set(failing))

    for name in regressions:
        annotate(
            name,
            f"not valid Python 3: {failing[name]}. This file is not in "
            f"tools/python3_baseline.txt, so this is a regression introduced "
            f"by the current change.",
        )

    for name in fixed:
        annotate(
            "tools/python3_baseline.txt",
            f"{name} now compiles but is still listed as failing. Remove its "
            f"line from tools/python3_baseline.txt so the baseline keeps "
            f"shrinking.",
        )

    remaining = len(failing) - len(regressions)
    print(f"Checked {checked} file(s).")
    print(f"Known Python 2 files remaining: {remaining} (baseline: {len(baseline)})")

    summary = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary:
        with open(summary, "a", encoding="utf-8") as handle:
            handle.write(
                f"\n**Python 3 migration:** {remaining} file(s) still to convert "
                f"under `Python/src`.\n"
            )

    if regressions or fixed:
        print(
            f"\n{len(regressions)} regression(s), {len(fixed)} stale baseline "
            f"entr(y/ies).",
            file=sys.stderr,
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
