#!/usr/bin/env python3
"""Fail when a build that used to run stops running.

CI gates the `compiler` and `runtime` jobs on `detect`, which looks for the
files those builds need. That gate is there for a good reason: a build job that
finds nothing to build, exits 0 and reports success is a worse lie than a red
build. But it has a failure mode of its own. Delete `CMakeLists.txt` and the
runtime jobs stop running, the workflow goes green, and the Actions tab says the
project is healthy because nothing was attempted.

That is the shape of every reward hack: make the measurement stop rather than
make the thing work. This turns it into a hard error.

The baseline is a ratchet, exactly like `tools/python3_baseline.txt`. A build
system listed in `required` must be present, and one that is present but not
listed must be added — so coverage can only grow. Removing an entry is a
deliberate, reviewable edit to this repository rather than a silent consequence
of deleting a file.

Usage:
    python tools/check_build_coverage.py            # check the tree
    python tools/check_build_coverage.py --update   # re-record what is present
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

BASELINE = Path(__file__).with_name("build_coverage.json")

# What each build system is recognised by. These are the same paths ci.yml's
# `detect` job probes; if one moves, both must change together, which is why the
# check names the file rather than re-implementing the detection.
PROBES: dict[str, str] = {
    "cmake": "CMakeLists.txt",
    "gradle": "Compiler/build.gradle",
}


def annotate(message: str, *, level: str = "error", path: str | None = None) -> None:
    """Print a GitHub Actions annotation, or a plain line when run locally."""
    if os.environ.get("GITHUB_ACTIONS") == "true":
        location = f" file={path}" if path else ""
        print(f"::{level}{location}::{message}")
    else:
        prefix = f"{path}: " if path else ""
        print(f"{level.upper()}: {prefix}{message}")


def load_baseline() -> list[str]:
    if not BASELINE.exists():
        return []
    data = json.loads(BASELINE.read_text(encoding="utf-8"))
    return sorted(data.get("required", []))


def present(root: Path) -> list[str]:
    return sorted(name for name, probe in PROBES.items() if (root / probe).exists())


def write_baseline(required: list[str]) -> None:
    BASELINE.write_text(
        json.dumps(
            {
                "_comment": (
                    "Build systems whose CI jobs must actually run. Generated by "
                    "tools/check_build_coverage.py --update. This list may only "
                    "grow: if a build system disappears from the tree its jobs "
                    "would silently skip and CI would go green having built "
                    "nothing, so the check fails instead."
                ),
                "required": sorted(required),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="repository root to check")
    parser.add_argument(
        "--update",
        action="store_true",
        help="re-record the build systems present, ratcheting coverage up",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    found = present(root)

    if args.update:
        write_baseline(found)
        print(f"Recorded {len(found)} build system(s): {', '.join(found) or 'none'}")
        return 0

    required = load_baseline()
    missing = [name for name in required if name not in found]
    unrecorded = [name for name in found if name not in required]

    for name in missing:
        annotate(
            f"the {name} build is in the baseline but {PROBES[name]} is gone. Its CI "
            f"jobs would skip and the run would go green having built nothing. "
            f"Restore it, or remove it from {BASELINE.name} in a commit that says why",
            path=PROBES[name],
        )

    for name in unrecorded:
        annotate(
            f"the {name} build is present but not in the baseline. Add it with "
            f"`python tools/check_build_coverage.py --update` so a later removal "
            f"cannot pass unnoticed",
            path=BASELINE.name,
        )

    print(f"Required: {', '.join(required) or 'none'}")
    print(f"Present:  {', '.join(found) or 'none'}")

    if missing or unrecorded:
        print(
            f"\n{len(missing)} missing, {len(unrecorded)} unrecorded. "
            f"AGENTS.md section 7 explains what each CI job does."
        )
        return 1

    print("Build coverage intact.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
