name: Build Docker Image

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile_full_image'
      - 'Docker/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile_full_image
        push: true
        tags: user/repo:image-tag

    - name: Run Docker Image
      run: docker run --rm user/repo:image-tag
